PLMVC/Models/ErrorViewModel.cs
namespace PLMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PLMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PLMVC.Models;
using System.Diagnostics;

namespace PLMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PLMVC/Controllers/RecetaMedicaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PLMVC.Controllers
{
    public class RecetaMedicaController : Controller
    {
        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Paciente paciente = new ML.Paciente();
            ML.Result resultPaciente = BL.Paciente.GetAll();
            if (resultPaciente.Correct)
            {
                paciente.Pacientes = resultPaciente.Objects;
                return View(paciente);
            }
            return View();
        }
        [HttpGet]
        public IActionResult GetRecetaMedica(int idPaciente, string nombrePaciente, string apellidoPaterno, string apellidoMaterno)
        {
          
            ML.RecetaMedica receta = new ML.RecetaMedica();
            receta.Paciente = new ML.Paciente();
            ML.Result result = BL.RecetaMedica.GetAll(idPaciente);

            ViewData["idPaciente"] = idPaciente;
            ViewData["nombrePaciente"] = nombrePaciente;
            ViewData["apellidoPaterno"] = apellidoPaterno;
            ViewData["apellidoMaterno"] = apellidoMaterno;

            if(result.Correct)
            {
                receta.RecetasMedicas = result.Objects;
                return View(receta);
            } else
            {
                return View(receta);
            }
            
        }
        [HttpGet]
        public IActionResult Form (int idPaciente, int? idReceta, string nombrePaciente, string apellidoPaterno, string apellidoMaterno)
        {
            ML.RecetaMedica receta = new ML.RecetaMedica ();
            receta.Paciente = new ML.Paciente ();
            receta.Paciente.IdPaciente = idPaciente;
            receta.Paciente.Nombre = nombrePaciente;
            receta.Paciente.ApellidoPaterno = apellidoPaterno;
            receta.Paciente.ApellidoMaterno = apellidoMaterno;

            if (idReceta == null) //add
            {
                return View(receta);
            } else
            {
                ML.Result result = BL.RecetaMedica.GetByIdReceta(idPaciente, idReceta.Value);
                if (result.Correct)
                {
                    receta = (ML.RecetaMedica)result.Object;
                    receta.Paciente = new ML.Paciente();
                    receta.Paciente.IdPaciente = idPaciente;
                    receta.Paciente.Nombre = nombrePaciente;
                    receta.Paciente.ApellidoPaterno = apellidoPaterno;
                    receta.Paciente.ApellidoMaterno = apellidoMaterno;
                    return View(receta);
                } else
                {
                    return View();
                }
                
            }
        }

        [HttpPost]
        public IActionResult Form(ML.RecetaMedica receta)
        {
            ViewData["idPaciente"] = receta.Paciente.IdPaciente;
            ViewData["nombrePaciente"] = receta.Paciente.Nombre;
            ViewData["apellidoPaterno"] = receta.Paciente.ApellidoPaterno;
            ViewData["apellidoMaterno"] = receta.Paciente.ApellidoMaterno;

            if (receta.IdReceta == 0)//add
            {
                ML.Result result = BL.RecetaMedica.Add(receta);
                if (result.Correct)
                {

                    ViewBag.Message = "La Receta se ha agreado correctamente";
                    return View("Modal");
                }
            } else
            {
                ML.Result result = BL.RecetaMedica.Update(receta);
                if (result.Correct)
                {
                    ViewBag.Message = "La Receta se ha actualizado correctamente";
                    return View("Modal");
                }
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int idPaciente, int idReceta, string nombrePaciente, string apellidoPaterno, string apellidoMaterno)
        {
            ViewData["idPaciente"] = idPaciente;
            ViewData["nombrePaciente"] = nombrePaciente;
            ViewData["apellidoPaterno"] = apellidoPaterno;
            ViewData["apellidoMaterno"] = apellidoMaterno;

            ML.Result result = BL.RecetaMedica.Delete(idPaciente, idReceta);
            if(result.Correct)
            {
                ViewBag.Message = "La Receta se ha eliminado correctamente";
                return View("Modal");
            } else
            {
                return View();
            }
        }
    }
}

PLMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PLMVC/Views/RecetaMedica/Form.cshtml
@model ML.RecetaMedica
@{
}

@using (Html.BeginForm("Form", "RecetaMedica", FormMethod.Post, new { enctype = "multipart/form-data", @class = "container" }))
{
    @Html.HiddenFor(model => model.IdReceta);
    @Html.HiddenFor(model => model.Paciente.IdPaciente);
    @Html.HiddenFor(model => model.Paciente.Nombre);
    @Html.HiddenFor(model => model.Paciente.ApellidoPaterno);
    @Html.HiddenFor(model => model.Paciente.ApellidoMaterno);

    <h2 class="text-center">Registro de Receta</h2>

    <div class="d-flex flex-column justify-content-center align-items-center">
        <div class="mb-3">
            <label class="d-flex justify-content-center mb-2">
                <i class="fa-solid fa-user-nurse fa-xl" style="color: #000000;"></i> Nombre del Médico
            </label>
            <div class="d-flex justify-content-center mb-2">
                @Html.TextBoxFor(model => model.NombreMedico, new { @class = "form-control" })
            </div>

            <label class="d-flex justify-content-center mb-2">
                <i class="fa-solid fa-calendar-days fa-xl" style="color: #000000;"></i> Fecha de la consulta
            </label>
            <div class="d-flex justify-content-center mb-2">
                @Html.TextBoxFor(model => model.FechaConsulta, new { @class = "form-control", @placeholder = "dd-mm-yyyy"})
            </div>

            <label class="d-flex justify-content-center mb-2">
                <i class="fa-solid fa-notes-medical fa-xl" style="color: #000000;"></i> Diagnóstico
            </label>

            <textarea name="Diagnostico"> @Model.Diagnostico </textarea>

            <label class="d-flex justify-content-center mb-2">
                <i class="fa-solid fa-comment-medical fa-xl" style="color: #000000;"></i> Notas Adicionales
            </label>

            <textarea name="NotasAdicionales"> @Model.NotasAdicionales </textarea>

        </div>


    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-6 text-center">
            <button type="submit" class="btn btn-success" id="botonGuardar">
                <span><i class="fa-solid fa-floppy-disk fa-xl" style="color: #000000;" id="iconoGuardar"></i></span>
                Guardar
            </button>
            <a href="@Url.Action("GetRecetaMedica", "RecetaMedica", new {idPaciente = Model.Paciente.IdPaciente, nombrePaciente = Model.Paciente.Nombre, apellidoPaterno = Model.Paciente.ApellidoPaterno, apellidoMaterno = Model.Paciente.ApellidoMaterno})" class="btn btn-secondary" id="btnRegresar">
                <span><i class="fa-solid fa-rotate-left fa-xl" style="color: #000000;" id="iconoRegresar"></i></span>
                Regresar
            </a>
        </div>
    </div>


}

PLMVC/Views/RecetaMedica/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ML.Paciente
@{
}

<h1 class="text-center mb-3">Pacientes</h1>

@if(Model.Pacientes != null)
{
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Apellido Paterno</th>
                    <th class="text-center">Apellido Materno</th>
                    <th class="text-center">Asignar Receta</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Paciente paciente in Model.Pacientes)
                {
                    <tr class="text-center align-middle">
                        <td class="fs-5">@paciente.Nombre</td>
                        <td class="fs-5">@paciente.ApellidoPaterno</td>
                        <td class="fs-5">@paciente.ApellidoMaterno</td>
                        <td>
                            <a class="btn btn-outline-secondary m-1" href="@Url.Action("GetRecetaMedica", "RecetaMedica", new {idPaciente = paciente.IdPaciente, nombrePaciente = paciente.Nombre, apellidoPaterno = paciente.ApellidoPaterno, apellidoMaterno = paciente.ApellidoMaterno})">
                                <i class="fas fa-plus fa-lg" style="color: #000;"></i>
                              </a>
                          </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    
} else
{
    <div class="alert alert-danger" role="alert">
        No hay pacientes
    </div>
}

<script>

</script>

PLMVC/Views/RecetaMedica/GetRecetaMedica.cshtml
@model ML.RecetaMedica
@{
}

<h1 class="text-center">Paciente: @ViewData["nombrePaciente"] @ViewData["apellidoPaterno"] @ViewData["apellidoMaterno"]</h1>

@if(Model.RecetasMedicas != null && Model.RecetasMedicas.Count > 0)
{
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th class="text-center">Eliminar Receta</th>
                    <th class="text-center">Nombre Médico</th>
                    <th class="text-center">Fecha Consulta</th>
                    <th class="text-center">Diagnostico</th>
                    <th class="text-center">Notas Adicionales</th>
                    <th class="text-center">Editar Receta</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.RecetaMedica receta in Model.RecetasMedicas)
                {
                    <tr class="text-center align-middle">
                        <td>
                            <a class="btn btn-outline-secondary m-1" href="@Url.Action("Delete", "RecetaMedica", new {idPaciente = ViewData["idPaciente"], idReceta = receta.IdReceta,  nombrePaciente = ViewData["nombrePaciente"], apellidoPaterno = ViewData["apellidoPaterno"], apellidoMaterno = ViewData["apellidoMaterno"]})" onclick="return confirm('¿Estás seguro de que deseas eliminar esta Receta?')">
                                <i class="fa-solid fa-eraser fa-xl" style="color: #050505;"></i>
                            </a>
                        </td>
                        <td class="fs-5">@receta.NombreMedico</td>
                        <td class="fs-5">@receta.FechaConsulta</td>
                        <td class="fs-5">@receta.Diagnostico</td>
                        <td class="fs-5">@receta.NotasAdicionales</td>
                        <td>
                            <a class="btn btn-outline-secondary m-1" href="@Url.Action("Form", "RecetaMedica", new {idPaciente = ViewData["idPaciente"], idReceta = receta.IdReceta,  nombrePaciente = ViewData["nombrePaciente"], apellidoPaterno = ViewData["apellidoPaterno"], apellidoMaterno = ViewData["apellidoMaterno"]})">
                                <i class="fa-solid fa-pen-clip fa-xl" style="color: #000000;"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
} else
{
    <div class="alert alert-danger text-center" role="alert">
        No hay recetas
    </div>
}

<div class="d-flex justify-content-center">
    <a class="text-center btn btn-success" href="@Url.Action("Form", "RecetaMedica", new {idPaciente = ViewData["idPaciente"], nombrePaciente = ViewData["nombrePaciente"], apellidoPaterno = ViewData["apellidoPaterno"], apellidoMaterno = ViewData["apellidoMaterno"]})">Agregar Receta</a>
</div>

PLMVC/Views/RecetaMedica/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Vale", "GetRecetaMedica", "RecetaMedica", new
                {
                idPaciente = ViewData["idPaciente"],
                nombrePaciente = ViewData["nombrePaciente"],
                apellidoPaterno = ViewData["apellidoPaterno"],
                apellidoMaterno = ViewData["apellidoMaterno"]
                }, new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PLMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PLMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PLMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PLMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecetaMedica" asp-action="GetAll">Receta Médica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PLMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>